<?php

module_load_include('inc', 'slideshow', 'includes/slideshow.entity');

/**
 * Implements hook_menu().
 */
function slideshow_menu() {

	$items = array();

	$items['admin/structure/slideshow/manage'] = array(
		'title' => 'Slideshow',
		'description' => 'Manage Slideshow Entities Structure',
		'page callback' => 'slideshow_admin_page',
		'file' => 'includes/slideshow.admin.inc',
		'access arguments' => array('administer slideshow entities'),
	);

	$items['slideshow/add'] = array(
		'title' => 'Add a slideshow Entity',
		'page callback' => 'slideshow_add',
		'access arguments' => array('create slideshow entities'),
		'file' => 'includes/slideshow.add.inc',
	);

  $items['slideshow/%slideshow/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slideshow_edit_form', 1),
    'access arguments' => array('edit slideshow entities'),
    'file' => 'includes/slideshow.edit.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;

}

/**
 * Implements hook_permission()
 */
function slideshow_permission() {
    return array(
    'administer slideshow entities' =>  array(
      'title' => t('Administer slideshow Entities'),
      'restrict access' => TRUE,
    ),
    'view slideshow entities' => array(
      'title' => t('View slideshow Entities'),
    ),
    'edit slideshow entities' => array(
      'title' => t('Edit slideshow Entities'),
    ),
    'create slideshow entities' => array(
      'title' => t('Create slideshow Entities'),
    ),
  );
}



/**
 * Implements hook_block_info().
 */
function slideshow_block_info() {
  $blocks['slideshow'] = array(
    'info' => t('Slideshow Block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function slideshow_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'slideshow':
      $block['content'] = array(
        '#markup' => theme('item_list', array('items' => slideshow_load_all(),'attributes' => array('id' => 'slideshow'))),
        '#attached' => array(
          'js' => array(drupal_get_path('module', 'slideshow') . '/slideshow.js'),
          'css' => array(drupal_get_path('module', 'slideshow') . '/slideshow.css.less'),
        ),
      );
      break;
  }
  return $block;
}


function slideshow_load_all(){
	$result = db_select('slideshow','s')
			->fields('s')
			->execute();
	$slides = array();
	while($row = $result->fetchAssoc()) {
		$slide = slideshow_load($row['sid']);
		$slide = slideshow_view($slide);
    $slides[] = render($slide);
	}
	return $slides;

}